#!/usr/bin/env bash
set -euo pipefail

# === Path to the newest snapshot generated by your fetcher ===
SRC="/Users/weero/fbf_fetcher/combined_20251107_1044.json"

# Copy it into the repo as combined.json
cp "$SRC" combined.json

# Commit & push only if the file changed
if ! git diff --quiet -- combined.json; then
  git add combined.json
  git commit -m "auto update $(date '+%Y-%m-%d %H:%M:%S')"
  git push origin main
fi
